### ISSUE TITLE
TensorRT on Jetson Nano

### ISSUE THREAD

**Issue by yury-sannikov** [timongentzsch/Jetson_Ubuntu20_Images#12]
Hi @timongentzsch, thank you for this great project!

Do you have any idea how to install TensorRT into the image?
The issue I'm facing is that according to the [Nvidia](https://developer.nvidia.com/nvidia-tensorrt-8x-download) the minimal TensorRT version for Ubuntu Focal requires CUDA 11.3.
However, per [this thread](https://forums.developer.nvidia.com/t/installing-cuda-11-x-on-jetson-nano/169109/3?u=user124577), CUDA 11 is not supported for the Jetson Nano yet.

**Comment by timongentzsch** [comment]
Hi @yury-sannikov ,
unfortunately you are forced to work on cuda 10.2 as long as you work on the jetson (i.e. on the nvidia tegra platform), since nvidia's drivers only support this cuda version. The current state of this repository already supports cuda 10.2 on ubuntu 20.04. Additionally I have added pytorch and opencv with cuda support as well.
I guess with tensorrt support you are referring to the python bindings which are currently not included. Fortunately, since the beginning of 2021, these have been added by Nvidia to the Tensorrt github repository ([Tensorrt bindings](https://github.com/NVIDIA/TensorRT/tree/main/python)) so that they can now be compiled for any python version.

I think I will update this repo by the end of next week (right now it's a bit in a messy state ;)) and at the same time add these bindings in an image.

**Comment by yury-sannikov** [comment]
Hi @timongentzsch thanks a lot. I was able to make the bindings compile. I ran simple tests and so far it's good. I put together a really hacky gist with my existing Dockerfile. Hope it may save some hours to someone else.
https://gist.github.com/yury-sannikov/d5bc8f7c8004ae6d1eb81a8d74cbaa6a

**Comment by aaronchongth** [comment]
Thank you @yury-sannikov for the detailed information of building it! I found that the compiled `.whl` file can be reused for other containers running the same library versions. So I committed the one I built with Jetpack 4.6.2 to [my own fork](https://github.com/aaronchongth/Jetson_Ubuntu20_Images/tree/master/assets), hope this is useful for other people.
