### ISSUE TITLE
Why compile ros2 instead if install from repo

### ISSUE THREAD

**Issue by amfern** [timongentzsch/Jetson_Ubuntu20_Images#2]
Great repo, thank you for your hard work. i was just wondering why did you decied to build ros2 from sources and not installing from debian packages in https://github.com/timongentzsch/Jetson_Ubuntu20_Images/blob/master/Dockerfile.ros2

**Comment by timongentzsch** [comment]
You're right one could absolutely install ros2 binaries via apt, however those binaries will only include the base packages. Since we were relying on image transport and opencv integration, we would have to install a part of the packages from source anyway. I found it easier in this case to use the rosinstall generator and build everything from source.

**Comment by amfern** [comment]
Just out of curiosity what packages would need to be recompiled with cuda support, does it also true for installing ros2 and running with cuda on amd64 computers?

**Comment by timongentzsch** [comment]
The ros packages itself do not rely on cuda. Honestly Im not 100 % sure if any of the ros packages (e.g. `cv-bridge` or `image-transport`) touch any cuda supported function of opencv. However, since I already had opencv with cuda support installed, I wanted to make sure to link against that version and not install the binaries (`libopencv-dev`) as dependencies.
